version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: postgres
    ports: 
        - 5432:5432

  backend:
    image: learnanylanguage-backend:latest
    restart: always
    ports:
      - 8180:8180      
